Rerun bundle install for rails LTS

diff --git a/test/setup_railsapp b/test/setup_railsapp
--- a/test/setup_railsapp
+++ b/test/setup_railsapp
@@ -81,6 +81,19 @@ actual_rails_version=`$rails -v`
 export GEM_PATH="$tmp_dir/gems:`gem environment gempath`"
 echo Set GEM_PATH=$GEM_PATH
 
+case "$BUNDLE_GEMFILE" in
+*_lts*)
+    echo "Re-running bundle with changed GEM_PATH (required by git install of rails lts) ..."
+    if ! bundle install ; then
+        echo "Test aborted (missing required gems)"
+        exit 2
+    else
+        echo bundle passed - lock file contains:
+        cat $BUNDLE_GEMFILE.lock
+        echo
+    fi
+    ;;
+esac
 echo Installing health_check as a gem into $tmp_dir/gems
 rm -f pkg/health_check-*.gem
 if env GEM_HOME=$tmp_dir/gems $rake install
