Use bundler version in the correct places

diff --git a/test/setup_railsapp b/test/setup_railsapp
--- a/test/setup_railsapp
+++ b/test/setup_railsapp
@@ -1,14 +1,6 @@
 #!/bin/bash
 
 route_prefix=medical_check
-
-err_report() {
-    echo "$0: Error on line $1 - aborted"
-    exit 1
-}
-
-trap 'err_report $LINENO' ERR
-
 # Any failure causes exit
 set -eE -o functrace
 
@@ -29,7 +21,6 @@ report_failure() {
 }
 
 trap 'report_failure "${BASH_LINENO[*]}" "$LINENO" "${FUNCNAME[*]:-script}" "$?" "$BASH_COMMAND"' ERR
-
 
 
 case "$1" in
@@ -74,14 +65,23 @@ mkdir -p tmp/gems
 if $rbenv_which bundle ; then
   echo Bundler is installed
 else
-  gem install bundler
+  gem install bundler ${BUNDLER_VERSION:+-v ${BUNDLER_VERSION}}
   $rehash
 fi
 
-echo "Running bundle with BUNDLE_GEMFILE=$BUNDLE_GEMFILE ..."
+which smarter_bundle || gem install smarter_bundler
+
+echo "Running smarter_bundle with BUNDLE_GEMFILE=$BUNDLE_GEMFILE ..."
 if ! smarter_bundle ; then
     echo "Test aborted (missing required gems)"
     exit 2
+elif [ ! -s $BUNDLE_GEMFILE.lock ] ; then
+    echo "Error: smarter_bundler return OK status BUT lock file ($BUNDLE_GEMFILE.lock) is missing!"
+    exit 3
+else
+    echo bundle passed - lock file contains:
+    cat $BUNDLE_GEMFILE.lock
+    echo
 fi
 $rehash
 
@@ -226,7 +226,7 @@ echo ================= Gemfile ===================
 cat Gemfile
 echo
 echo running bundle install
-smarter_bundle ${BUNDLER_VERSION:+_${BUNDLER_VERSION}_} install
+smarter_bundle install
 $rehash
 echo "Using binstubs in $railsapp/bin for rails and rake commands"
 rails="$railsapp/bin/rails"
