Report line number of error

diff --git a/test/setup_railsapp b/test/setup_railsapp
--- a/test/setup_railsapp
+++ b/test/setup_railsapp
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+err_report() {
+    echo "$0: Error on line $1 - aborted"
+    exit 1
+}
+
+trap 'err_report $LINENO' ERR
+
 # Any failure causes exit
 set -e
 
